CREATE TABLE `CAR_INFO` (
	`PK_CAR_ID`	VARCHAR(50)	NOT NULL,
	`CAR_NAME`	VARCHAR(255)	NULL,
	`FK_COMMON_CODES_COMPANY`	VARCHAR(50)	NULL,
	`FK_COMMON_CODES_YEARS`	VARCHAR(50)	NULL
);
CREATE TABLE `CAR_COMMON_CODES` (
	`FK_COMMON_CODES`	VARCHAR(50)	NOT NULL,
	`PART_NAME`	VARCHAR(255)	NULL,
	`NAME`	VARCHAR(255)	NULL
);
ALTER TABLE `CAR_INFO` ADD CONSTRAINT `PK_CAR_INFO` PRIMARY KEY (
	`PK_CAR_ID`
);
ALTER TABLE `CAR_COMMON_CODES` ADD CONSTRAINT `PK_COMMON_CODES` PRIMARY KEY (
	`FK_COMMON_CODES`
);

-- ------------------

INSERT INTO `CAR_INFO` (`PK_CAR_ID`, `CAR_NAME`, `FK_COMMON_CODES_COMPANY`, `FK_COMMON_CODES_YEARS`) VALUES
('PK_C_01', '소나타', 'PK_COM_01', 'PK_YEAR_04'),
('PK_C_02', '쏘렌토', 'PK_COM_02', 'PK_YEAR_02'),
('PK_C_03', '카마로', 'PK_COM_03', 'PK_YEAR_03'),
('PK_C_04', '3시리즈', 'PK_COM_04', 'PK_YEAR_01'),
('PK_C_05', 'E클래스', 'PK_COM_05', 'PK_YEAR_05'),
('PK_C_06', '소나타', 'PK_COM_01', 'PK_YEAR_02');

INSERT INTO `CAR_COMMON_CODES` (`FK_COMMON_CODES`, `PART_NAME`, `NAME`) VALUES
('PK_COM_01', 'COMPANY', '현대'),
('PK_COM_02', 'COMPANY', '기아'),
('PK_COM_03', 'COMPANY', '쉐보레'),
('PK_COM_04', 'COMPANY', 'BMW'),
('PK_COM_05', 'COMPANY', '벤츠'),
('PK_YEAR_01', 'YEARS', '2017'),
('PK_YEAR_02', 'YEARS', '2018'),
('PK_YEAR_03', 'YEARS', '2019'),
('PK_YEAR_04', 'YEARS', '2020'),
('PK_YEAR_05', 'YEARS', '2021');

-- ------------------

SELECT * FROM CAR_INFO;
SELECT * FROM CAR_COMMON_CODES;

SELECT CI.*, CCC.NAME, CCY.NAME
FROM CAR_INFO CI
	JOIN CAR_COMMON_CODES CCC
    ON CCC.FK_COMMON_CODES = CI.FK_COMMON_CODES_COMPANY
	JOIN CAR_COMMON_CODES CCY
    ON CCY.FK_COMMON_CODES = CI.FK_COMMON_CODES_YEARS
    ;
