-- CREATE TABLE `VISITOR` (
-- 	`VISITOR_ID`	VARCHAR(255)	NOT NULL,
-- 	`NOTICE_ID`	VARCHAR(255)	NOT NULL,
-- 	`VISITOR_NAME`	VARCHAR(255)	NULL
-- );

INSERT INTO VISITOR 
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES 
('VISITE_01', 'NOTICE_01', '홍길동');
-- NOTICE_ID는 FK

INSERT INTO VISITOR 
(VISITOR_ID, NOTICE_ID, VISITOR_NAME)
VALUES 
('VISITE_10', 'NOTICE_05', '강수민')
, ('VISITE_11', 'NOTICE_05', '백지영')
, ('VISITE_12', 'NOTICE_05', '박정희');

SELECT *
FROM NOTICE;

SELECT *
FROM VISITOR;
