CREATE TABLE `USER` (
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`GENDER_ID`	VARCHAR(50)	NOT NULL,
	`USER_NAME`	VARCHAR(255)	NULL,
	`USER_AGE`	VARCHAR(255)	NULL,
	`USER_PHONENUMBER`	VARCHAR(255)	NULL,
	`USER_EMAIL`	VARCHAR(255)	NULL
);

CREATE TABLE `GENDER` (
	`GENDER_ID`	VARCHAR(50)	NOT NULL,
	`GENDER_USER`	VARCHAR(255)	NULL
);

CREATE TABLE `HOBBY` (
	`HOBBY_ID`	VARCHAR(50)	NOT NULL,
	`HOBBY_USER`	VARCHAR(255)	NULL
);

CREATE TABLE `ADDRESS` (
	`ADDRESS_ID`	VARCHAR(50)	NOT NULL,
	`ADDRESS_USER`	VARCHAR(255)	NULL
);

CREATE TABLE `USER_HOBBY` (
	`USER_HOBBY_ID`	VARCHAR(50)	NOT NULL,
	`HOBBY_ID2`	VARCHAR(50)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`GENDER_ID`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `USER_ADDRESS` (
	`USER_ADDRESS_ID`	VARCHAR(50)	NOT NULL,
	`ADDRESS_ID2`	VARCHAR(50)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`GENDER_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_ID`,
	`GENDER_ID`
);

ALTER TABLE `GENDER` ADD CONSTRAINT `PK_GENDER` PRIMARY KEY (
	`GENDER_ID`
);

ALTER TABLE `HOBBY` ADD CONSTRAINT `PK_HOBBY` PRIMARY KEY (
	`HOBBY_ID`
);

ALTER TABLE `ADDRESS` ADD CONSTRAINT `PK_ADDRESS` PRIMARY KEY (
	`ADDRESS_ID`
);

ALTER TABLE `USER_HOBBY` ADD CONSTRAINT `PK_USER_HOBBY` PRIMARY KEY (
	`USER_HOBBY_ID`,
	`HOBBY_ID2`,
	`USER_ID`,
	`GENDER_ID`
);

ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `PK_USER_ADDRESS` PRIMARY KEY (
	`USER_ADDRESS_ID`,
	`ADDRESS_ID2`,
	`USER_ID`,
	`GENDER_ID`
);

ALTER TABLE `USER` ADD CONSTRAINT `FK_GENDER_TO_USER_1` FOREIGN KEY (
	`GENDER_ID`
)
REFERENCES `GENDER` (
	`GENDER_ID`
);

ALTER TABLE `USER_HOBBY` ADD CONSTRAINT `FK_HOBBY_TO_USER_HOBBY_1` FOREIGN KEY (
	`HOBBY_ID2`
)
REFERENCES `HOBBY` (
	`HOBBY_ID`
);

ALTER TABLE `USER_HOBBY` ADD CONSTRAINT `FK_USER_TO_USER_HOBBY_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);

ALTER TABLE `USER_HOBBY` ADD CONSTRAINT `FK_USER_TO_USER_HOBBY_2` FOREIGN KEY (
	`GENDER_ID`
)
REFERENCES `USER` (
	`GENDER_ID`
);

ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `FK_ADDRESS_TO_USER_ADDRESS_1` FOREIGN KEY (
	`ADDRESS_ID2`
)
REFERENCES `ADDRESS` (
	`ADDRESS_ID`
);

ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `FK_USER_TO_USER_ADDRESS_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);

ALTER TABLE `USER_ADDRESS` ADD CONSTRAINT `FK_USER_TO_USER_ADDRESS_2` FOREIGN KEY (
	`GENDER_ID`
)
REFERENCES `USER` (
	`GENDER_ID`
);

