CREATE TABLE `MOVIE` (
	`MOVIE_ID`	VARCHAR(50)	NOT NULL,
	`MOVIE_TITLE`	VARCHAR(255)	NULL
);

CREATE TABLE `TITLE` (
	`TITLE_ID`	VARCHAR(50)	NOT NULL,
	`MOVIE_ID`	VARCHAR(50)	NOT NULL,
	`TITLE_REVIEW`	VARCHAR(255)	NULL
);

CREATE TABLE `REVIEW` (
	`REVIEW_ID`	VARCHAR(50)	NOT NULL,
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`TITLE_ID`	VARCHAR(50)	NOT NULL,
	`MOVIE_ID`	VARCHAR(50)	NOT NULL,
	`REVIEW_COMMENT`	VARCHAR(255)	NULL,
	`REVIEW_DATE`	DATETIME	NULL,
	`REVIEW_RATING`	VARCHAR(255)	NULL
);

CREATE TABLE `USER` (
	`USER_ID`	VARCHAR(50)	NOT NULL,
	`USER_REVIEW`	VARCHAR(255)	NULL
);

ALTER TABLE `MOVIE` ADD CONSTRAINT `PK_MOVIE` PRIMARY KEY (
	`MOVIE_ID`
);

ALTER TABLE `TITLE` ADD CONSTRAINT `PK_TITLE` PRIMARY KEY (
	`TITLE_ID`,
	`MOVIE_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `PK_REVIEW` PRIMARY KEY (
	`REVIEW_ID`,
	`USER_ID`,
	`TITLE_ID`,
	`MOVIE_ID`
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`USER_ID`
);

ALTER TABLE `TITLE` ADD CONSTRAINT `FK_MOVIE_TO_TITLE_1` FOREIGN KEY (
	`MOVIE_ID`
)
REFERENCES `MOVIE` (
	`MOVIE_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_USER_TO_REVIEW_1` FOREIGN KEY (
	`USER_ID`
)
REFERENCES `USER` (
	`USER_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_TITLE_TO_REVIEW_1` FOREIGN KEY (
	`TITLE_ID`
)
REFERENCES `TITLE` (
	`TITLE_ID`
);

ALTER TABLE `REVIEW` ADD CONSTRAINT `FK_TITLE_TO_REVIEW_2` FOREIGN KEY (
	`MOVIE_ID`
)
REFERENCES `TITLE` (
	`MOVIE_ID`
);

