CREATE TABLE `CAR` (
	`CAR_ID`	VARCHAR(50)	NOT NULL,
	`CAR_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `COMPANY` (
	`COMPANY_ID`	VARCHAR(50)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `YEAR` (
	`YEAR_ID`	VARCHAR(50)	NOT NULL,
	`YEAR_CAR`	VARCHAR(255)	NULL
);

CREATE TABLE `OPTION` (
	`OPTION_ID`	VARCHAR(50)	NOT NULL,
	`OPTION_NAME`	VARCHAR(255)	NULL
);

CREATE TABLE `CAR_COMPANY_YEAR` (
	`CAR_COMPANY_YEAR_ID`	VARCHAR(50)	NOT NULL,
	`YEAR_ID2`	VARCHAR(50)	NOT NULL,
	`COMPANY_ID`	VARCHAR(50)	NOT NULL,
	`CAR_ID`	VARCHAR(50)	NOT NULL,
	`OPTION_ID`	VARCHAR(50)	NOT NULL
);

ALTER TABLE `CAR` ADD CONSTRAINT `PK_CAR` PRIMARY KEY (
	`CAR_ID`
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (
	`COMPANY_ID`
);

ALTER TABLE `YEAR` ADD CONSTRAINT `PK_YEAR` PRIMARY KEY (
	`YEAR_ID`
);

ALTER TABLE `OPTION` ADD CONSTRAINT `PK_OPTION` PRIMARY KEY (
	`OPTION_ID`
);

ALTER TABLE `CAR_COMPANY_YEAR` ADD CONSTRAINT `PK_CAR_COMPANY_YEAR` PRIMARY KEY (
	`CAR_COMPANY_YEAR_ID`,
	`YEAR_ID2`,
	`COMPANY_ID`,
	`CAR_ID`,
	`OPTION_ID`
);

ALTER TABLE `CAR_COMPANY_YEAR` ADD CONSTRAINT `FK_YEAR_TO_CAR_COMPANY_YEAR_1` FOREIGN KEY (
	`YEAR_ID2`
)
REFERENCES `YEAR` (
	`YEAR_ID`
);

ALTER TABLE `CAR_COMPANY_YEAR` ADD CONSTRAINT `FK_COMPANY_TO_CAR_COMPANY_YEAR_1` FOREIGN KEY (
	`COMPANY_ID`
)
REFERENCES `COMPANY` (
	`COMPANY_ID`
);

ALTER TABLE `CAR_COMPANY_YEAR` ADD CONSTRAINT `FK_CAR_TO_CAR_COMPANY_YEAR_1` FOREIGN KEY (
	`CAR_ID`
)
REFERENCES `CAR` (
	`CAR_ID`
);

ALTER TABLE `CAR_COMPANY_YEAR` ADD CONSTRAINT `FK_OPTION_TO_CAR_COMPANY_YEAR_1` FOREIGN KEY (
	`OPTION_ID`
)
REFERENCES `OPTION` (
	`OPTION_ID`
);

