CREATE TABLE `NOTICE` (
	`NOTICE_ID`	VARCHAR(255)	NOT NULL,
	`TOPIC`	VARCHAR(255)	NULL,
	`WRITER`	VARCHAR(255)	NULL
);

CREATE TABLE `COMMENT` (
	`COMMENT_ID`	VARCHAR(255)	NOT NULL,
	`NOTICE_ID`	VARCHAR(255)	NOT NULL,
	`COMMENT_DETAIL`	VARCHAR(255)	NULL
);

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_ID`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `PK_COMMENT` PRIMARY KEY (
	`COMMENT_ID`,
	`NOTICE_ID`
);

ALTER TABLE `COMMENT` ADD CONSTRAINT `FK_NOTICE_TO_COMMENT_1` FOREIGN KEY (
	`NOTICE_ID`
)
REFERENCES `NOTICE` (
	`NOTICE_ID`
);

